.github/workflows/checklinks.yml

Fixing issue where report does not get generated

Updating workflow

---

.github/workflows/checklinks.yml
.lychee/out.md

Removing auto creation of issues until issue is resolved

Hugoabernier patch 1

---

.github/ISSUE_TEMPLATE/ArticleIssue.md
.github/ISSUE_TEMPLATE/ArticleSuggestion.md
.github/ISSUE_TEMPLATE/Question.md
.github/PULL_REQUEST_TEMPLATE.md

Added PR template and issues

---

content/microsoft-identity-platform-community-call/microsoft-identity-platform-community-call-february-2022/index.md
content/microsoft-identity-platform-community-call/microsoft-identity-platform-community-call-january-2022/index.md

more cleanup

---

CONTRIBUTING.md

- fixes #53 
🎯 Aim
The aim of this PR is to introduce a small fix to the contributing guidance

Added small fix in contributing md guide

---

content/post/community-sample-faqs-with-propertyfieldcollectiondata/index.md

replaces img shortcodes by md syntax

replaces img shortcodes by md syntax images

---

content/post/community-sample-faqs-with-propertyfieldcollectiondata/index.md

> Used a different way of showing the images
> Fixed the images names and also made sure it is same name as it seems to be case sensitive.

Update the display of the images and also fixed the images names

---

content/microsoft-365-platform-community-call/2022-04-12/index.md
content/microsoft-365-pnp-weekly/episode-161/index.md

1. attempt to fix FM

---

content/post/how-to-use-oh-my-posh-with-PnPPowerShell/index.md

new article in the making

---

content/post/how-to-use-oh-my-posh-with-PnPPowerShell/index.md

adds cortrect title

---

content/post/how-to-use-oh-my-posh-with-PnPPowerShell/index.md

adds structure

---

content/post/how-to-use-oh-my-posh-with-PnPPowerShell/index.md

minor edit before publish

---

content/microsoft-365-developer-community-call/2022-04-14/index.md
content/microsoft-365-platform-community-call/2022-04-12/index.md

minor edits

---

content/post/save-data-to-app-personal-folder/index.md

- fixes #64
🎯 Aim
The aim of this PR is to fix broken src in images in article I added.

🐛🔨 bug fix - broken img src in save data to app folder article

---

content/microsoft-365-platform-community-call/2022-04-12/files/placeholder.md

adds placeholder

---

content/microsoft-365-developer-community-call/2022-04-14/files/placeholder.md

adds placeholder to general call

---

content/microsoft-365-developer-community-call/2022-04-14/index.md

minor formatting

---

content/post/how-to-use-oh-my-posh-with-PnPPowerShell/index.md

formatting fixes

---

content/post/how-to-use-oh-my-posh-with-PnPPowerShell/index.md

Added information on how the site information gets displayed in the `oh-my-posh`'s M365Princess theme as per the request in [this tweet](https://twitter.com/michael_maillot/status/1514842880258543622).

adds details on how the site info gets displayed

---

content/microsoft-365-platform-community-call/2022-04-19/index.md

first attempt to fix fm

---

content/microsoft-viva-and-spfx-community-call/2022-04-21/index.md

add-deck-to-2022-04-21-spfx-call

---

content/post/how-to-get-started-deploying-Azure-resources-using-bicep/index.md
content/post/microsoft-365-self-service-using-power-apps/index.md

fixes image ref

---

content/post/microsoft-365-self-service-using-power-apps/index.md

formatting

---

content/post/microsoft-365-self-service-using-power-apps/index.md

attempts preview for blog post

---

CONTRIBUTING.md

improves contributing  guide

---

content/microsoft-365-platform-community-call/2022-04-26/index.md

Updating time for 27th of April blog post

Updating time for 27th of April blog post

---

content/microsoft-365-platform-community-call/2022-04-26/index.md

Updating time for 27th of April blog post

Fixing dates for the 27th blog post

---

content/post/how-to-rename-files-in-SharePoint-with-Power-Automate/index.md

removing unnecessary h2

---

content/post/how-to-use-oh-my-posh-with-PnPPowerShell/index.md

added new `oh-my-posh` install instructions

docs: new `oh-my-posh` install instructions

---

content/pnp-powershell/pnp-powershell-v1-10/index.md
content/post/getting-started-with-sharepoint-s-custom-column-formatting/index.md
content/post/getting-started-with-sharepoint-s-custom-view-formatting/index.md

corrects fm

---

content/post/how-to-rename-files-in-SharePoint-with-Power-Automate/index.md

minor change

---

content/post/get-started-with-adaptive-cards/index.md
content/post/getting-started-with-sharepoint-s-custom-column-formatting/index.md
content/post/how-to-get-started-with-http-requests-in-power-automate/index.md
content/post/setting-up-https-for-teams-tabs-projects-without-ngrok/index.md
content/post/use-cli-for-microsoft-365-to-recognize-contributions/index.md
content/post/what-is-a-dev-tenant-and-why-would-you-want-one/index.md

pins new posts to the top

---

content/microsoft-365-pnp-community/microsoft-365-platform-community-pnp-february-2022-update/index.md
content/post/azure-cloud-shell-issue-when-using-cli-for-microsoft-365/index.md
content/post/get-started-with-adaptive-cards/index.md
content/post/monitor-and-notify-m365-health-using-cli-for-microsoft-365/index.md
content/post/new-microsoft-365-patterns-and-practices-pnp-team-members/index.md

corrects image links

---

content/post/get-started-with-adaptive-cards/index.md
content/post/getting-started-with-sharepoint-s-custom-column-formatting/index.md
content/post/introduction-to-tokens/index.md
content/post/use-cli-for-microsoft-365-to-recognize-contributions/index.md

small adjustments

---

content/microsoft-365-developer-community-call/2022-04-28/index.md

Updating publishing time for 28th of April call summary

Updating publishing time for 28th of April call summary

---

layouts/_default/single.html

Updated thumbnail image to be resized properly. Solves #123
A minor tweak in the way the header thumbnail image is rendered. Left is the current situation that is live, right is the way the thumbnail will be rendered if this PR is accepted.

Updated thumbnail image to be resized properly. Solves #123

---

themes/reader-hugo/layouts/partials/head.html

Solves #126
Minor tweak to template HTML to use Page description instead of the Hugo template description

Updated page description. Solves #126

---

content/post/new-community-blog-platform/index.md

removes 2nd parker

---

content/post/create-an-event-page-with-sharepoint-sharepoint-spaces-and/index.md

1st attempt to fix yaml issue

---

config/_default/params.toml

Added default description. Solves #126

Added default description. Solves #126

---

content/post/how-to-use-oh-my-posh-with-PnPPowerShell/index.md

docs: updated code to add in profile file

---

config.toml
layouts/_default/single.html

Added viewcount to every page and increased build timeout

Added viewcount to pages

---

content/microsoft-365-pnp-weekly/episode-164/index.md
content/post/how-to-start-a-new-spfx-web-part-project-with-microsoft-graph/index.md

minor edits on metadata an removing localization from URLs

---

content/microsoft-365-pnp-weekly/episode-164/index.md

Updating publishing time for PnP Weekly 164
- [x ] Content fix

Updating publishing time for PnP Weekly 164

---

CONTRIBUTING.md

adds info on short how to, some format fixes

---

layouts/partials/head.html

Revert #127. Solved #151

---

layouts/_default/single.html

Updated alt tag and added title to images

Fixed mislabeled viewcount

---

layouts/_default/list.html
layouts/_default/single.html

extend single html to m365 platform call as well

---

content/microsoft-viva-and-spfx-community-call/2022-05-05/index.md

add-2022-05-05-platform-call

---

content/microsoft-365-platform-community-call/2022-05-03/index.md
content/microsoft-365-pnp-weekly/episode-164/index.md

adjustments

---

content/microsoft-viva-and-spfx-community-call/2022-05-05/index.md

initiate page publishing

---

layouts/partials/head.html

Implemented correct twitter image. Solves #124

Implemented correct twitter image. Solves #124

---

archetypes/microsoft-365-pnp-community/index.md
content/microsoft-365-developer-community-call/microsoft-365-developer-community-call-recording-30th-of/index.md
content/microsoft-365-platform-community-update/22-05-10/index.md
content/microsoft-365-pnp-community/microsoft-365-platform-community-pnp-february-2022-update/index.md
content/microsoft-365-pnp-weekly/episode-162/index.md
content/microsoft-viva-and-spfx-community-call/sharepoint-framework-community-call-21st-of-october-2021/index.md
content/post/how-to-create-a-custom-connector-for-your-own-azure-hosted-api/index.md
content/post/pnp-powershell-to-manage-list-designs-and-create-lists-libraries/index.md

Monthly summary WIP 2

---

content/microsoft-365-platform-community-update/22-05-10/index.md

monthly summary WIP 3

---

content/microsoft-365-platform-community-update/22-05-10/index.md

adds latest Dev blog post

---

content/microsoft-365-pnp-weekly/episode-165/index.md

PnP Weekly 165 publishing

---

content/microsoft-365-platform-community-update/22-05-10/index.md

Moving one person to right category in the monthly summary for May 2022.

Fixing Mathijs's company in may summary

---

content/microsoft-365-platform-community-call/2022-05-10/index.md

completed-2022-05-10-platform-call-post

---

content/office-add-ins-community-call/2022-04-13/index.md

attempt to improve formatting

---

content/microsoft-365-platform-community-update/22-05-10/index.md

Fixed a typo in the company name where I am currently employed at.
Also, I have removed myself from the list of MS employees.

Fix personal information in latest community update

---

README.md

[Chore] removed spacing to trigger rebuild

[Chore] removed spacing

---

content/microsoft-365-developer-community-call/2022-05-12/index.md

Updating agenda items for 12th of May

---

content/microsoft-365-developer-community-call/2022-05-12/index.md

Time marker fix for May 12th call

---

layouts/_default/rss.xml

Updated RSS view. Solves #145
- limit to the last 25 items
- Added image in preview
- Added categories
- Added Author

Updated RSS view. Solves #145

---

content/office-add-ins-community-call/2022-04-13/index.md

adds video

---

content/office-add-ins-community-call/2022-05-11/index.md

- [ x] Content fix
Adding Q&A for the May 2022 blog for Office Add-ins

Added Q&A and some minor fixes

---

content/office-add-ins-community-call/2022-05-11/index.md

This is to publish the May 2022 Office Add-ins community call blog.

Update from draft to published

---

content/adaptive-cards-community-call/adaptive-cards-community-call-may-2022/index.md

add-2-post-demo-features-called-out-by-josh

---

content/power-platform-community-call/power-apps-community-call-may-2022/index.md

fixes fm in ppcc-replaced double by single quotes

---

.lychee/.lycheeignore

Updated ignore file. Solves part of #202

Updated ignore file. Solves part of #202

---

.lychee/.lycheeignore
content/microsoft-365-platform-community-update/microsoft-365-platform-call-18th-of-january-2022/index.md
content/microsoft-365-platform-community-update/microsoft-365-platform-call-25th-of-january-2022/index.md
content/post/browser-local-storage-using-pnpclientstorage.md
content/post/how-to-set-up-tailwind-css-in-a-spfx-project/index.md
content/post/how-to-use-oh-my-posh-with-PnPPowerShell/index.md
content/post/learn-to-debug-your-power-apps/index.md
content/post/pnp-powershell-or-cli-for-microsoft-365-or-both-or-other/index.md
content/post/struggling-with-using-spfx-on-sharepoint-2016-let-me-help.md
content/power-platform-community-call/power-apps-community-call-august-2021/index.md
content/power-platform-community-call/power-apps-community-call-march-2021/index.md

Finalizes content and exclusions. Solves #202

Finalizes content and exclusions. Solves #202

---

content/microsoft-365-pnp-weekly/episode-167/index.md

Publishing PnP Weekly episode 167

Publishing PnP Weekly episode 167

---

.lychee/.lycheeignore
content/microsoft-365-platform-community-update/22-05-10/index.md
content/microsoft-365-pnp-community/microsoft-365-pnp-community-august-2021-update/index.md
content/post/monitor-and-notify-m365-health-using-cli-for-microsoft-365/index.md

Content changes and lichee update. Solves #202

Content changes and lichee update. Solves #202

---

.lychee/.lycheeignore
content/post/community-sample-news-ticker-app-spfx-extensions/index.md

Last link fixes. Solves #202

---

content/microsoft-365-pnp-weekly/microsoft-365-pnp-weekly-episode-122/index.md

Fixed typo in twitter link. Solves #202

Fixed typo in twitter link. Solves #202

---

.github/workflows/checklinks.yml

Fix output for link checking. Solves #239

Fix output for link checking. Solves #239

---

content/microsoft-365-platform-community-call/2022-05-24/index.md

add-vesa-name-to-2022-05-24-platform-call-demo-in-post

---

content/cli-for-microsoft-365/cli-for-microsoft-365-v5-3/index.md

Updates time on the CLI v5.3 announcement

---

content/microsoft-365-pnp-weekly/episode-168/index.md

Fixing typo in the episode 168

Fixing typo in the episode 168

---

.github/workflows/checklinks.yml

Fixed link issue creation error. Solves #244

Fixed link issue creation error. Solves #244

---

content/microsoft-viva-and-spfx-community-call/2022-06-02/index.md

fixes front matter - no duplicate double quotes allowed

---

content/microsoft-viva-and-spfx-community-call/2022-06-02/index.md
content/post/list-formatting-view-the-contents-of-a-file-with-file-preview-card/index.md

removes blog post 

---

content/adaptive-cards-community-call/adaptive-cards-community-call-october-2021/index.md
content/m365-dev-podcast/microsoft-365-developer-podcast-code-like-a-pro-in-c-with-jort.md
content/microsoft-365-developer-community-call/microsoft-365-developer-community-call-recording-11th-of/index.md
content/microsoft-365-developer-community-call/microsoft-365-developer-community-call-recording-25th-of/index.md
content/microsoft-365-platform-community-update/22-06-14/index.md
content/microsoft-identity-platform-community-call/microsoft-identity-platform-community-call-december-2021/index.md
content/microsoft-identity-platform-community-call/microsoft-identity-platform-community-call-january-2022/index.md
content/post/microsoft-365-developer-account/Images/index.md

link fixes

---

content/post/microsoft-365-developer-account/Images/index.md

fixes link checker issues

---

content/microsoft-365-platform-community-update/22-06-14/index.md

June monthly summary

---

content/office-add-ins-community-call/2022-06-08/index.md

N/A
Changed the draft attribute value to `false` to publish the blog post.
None.

[Office Add-ins] Publish June blog post

---

content/microsoft-365-platform-community-call/2022-06-14/index.md

add-2022-06-14-updated-platform-call-post

---

content/microsoft-365-platform-community-call/2022-06-14/index.md

Fixing embedded YouTube video

---

content/post/excel-file-tricks-with-powerautomate/index.md

minor formatting edits

---

content/post/community-sample-faqs-with-propertyfieldcollectiondata/index.md
content/post/excel-file-tricks-with-powerautomate/index.md

excludes two posts from build

---

config.toml

ups timeout

---

content/microsoft-viva-and-spfx-community-call/2022-06-16/index.md

add-2022-06-16-updated-spfx-call-post

---

.github/workflows/gh-pages.yml

Reset to previous Hugo version to fix build problems

Reset to previous Hugo version

---

content/post/community-sample-faqs-with-propertyfieldcollectiondata/index.md
content/post/excel-file-tricks-with-powerautomate/index.md

adds the 2 blog posts again

---

content/microsoft-365-platform-community-call/2022-06-21/index.md

add-2022-06-21-updated-platform-call-post

---

content/post/we-love-community/index.md

adjust pub date

---

content/microsoft-365-platform-community-call/2022-06-28/index.md

fix-wording-2022-06-28-platform-post

---

content/post/new-pnp-team-members-june-2022/index.md

Publishing new blog post on the PnP team members

---

content/microsoft-365-pnp-weekly/episode-173/index.md

publish pnp weekly 173

---

content/microsoft-365-pnp-weekly/episode-173/index.md

add-podcast-2022-07-04-pnp-weekly-ep-173

---

content/cli-for-microsoft-365/cli-for-microsoft-365-v5-6/index.md

Update timestamp to resolve issue with post not being rendered

Update timestamp on CLI v5.6 announcement post

---

content/microsoft-365-platform-community-update/22-08-12/index.md

Added SiC Contributors

---

content/post/updating-your-list-forms-using-your-provisioning-tool-of-choice/index.md

No related issue. Mentioned in [Microsoft 365 PnP Weekly – Episode 174](https://youtu.be/hmZPbdvgte4?t=3537)
Resolved the formatting issues on article [Updating your list forms using your provision tool of choice](https://pnp.github.io/blog/post/updating-your-list-forms-using-your-provisioning-tool-of-choice/). 
The PowerShell samples and the image weren't loading in properly.

Resolving formatting issues on article `Updating your list forms using your provision tool of choice`

---

content/microsoft-365-pnp-weekly/episode-175/index.md

add-2022-08-23-podcast-to-pnpweekly-ep175-post

---

content/cli-for-microsoft-365/cli-for-microsoft-365-v5-7/index.md

Closes #540
Update wording in the CLI for Microsoft 5.7 update blog about bookings businesses.

Update wording in CLI 5.7 update blog about bookings businesses. Closes #540

---

.github/workflows/gh-pages.yml

Implemented shallow build. Solves #144

Implemented shallow build. Solves #144

---

content/microsoft-365-pnp-weekly/episode-177/index.md

add-podcast-2022-09-05-pnp-weekly-ep-177-post

---

content/microsoft-365-pnp-weekly/episode-178/index.md

Publishing PnP Weekly episode 178

Publishing PnP Weekly episode 178

---

content/office-add-ins-community-call/2022-06-08/index.md

2022-06-08-update-video-in-june-add-ins-post

---

content/microsoft-365-pnp-weekly/episode-179/index.md

switch-draft-to-false-pnp-weekly-ep179

---

.devcontainer/devcontainer.json
.github/workflows/gh-pages.yml
config/_default/config.toml
layouts/_default/_markup/render-image.html
layouts/_default/baseof.html
layouts/_default/list.html
layouts/_default/single.html
layouts/homepage/single.html
layouts/partials/default.html
layouts/partials/footer.html
layouts/partials/head.html
themes/reader-hugo/layouts/partials/header.html

Updated hugo version. Partially solves #144

Updated hugo version. Partially solves #144

---

.devcontainer/devcontainer.json
.github/workflows/gh-pages.yml
config/_default/config.toml
layouts/_default/_markup/render-image.html
layouts/_default/baseof.html
layouts/_default/list.html
layouts/_default/single.html
layouts/homepage/single.html
layouts/partials/default.html
layouts/partials/footer.html
layouts/partials/head.html
themes/reader-hugo/layouts/partials/header.html

Revert "Updated hugo version. Partially solves #144"

---

content/weekly-agenda/22-10-03/index.md

Publishing weekly summary

---

content/microsoft-365-platform-community-call/2022-10-04/index.md

added-together-mode-still-image-to-platform-post-2022-10-04

---

content/weekly-agenda/22-10-10/index.md

Updates on the weekly summary for community agenda and events

---

config.toml
config/_default/config.toml

- fixes #635
- enables GA & GSC to help ID SEO issues & optimization ops

Add support for GA & GSC

---

content/microsoft-365-platform-community-call/2022-10-18/index.md

Forcing publishing of the platform call blog post

---

content/weekly-agenda/22-10-10/index.md

fixes types -2

---

content/weekly-agenda/22-10-17/index.md

fixes type

---

content/weekly-agenda/22-10-24/index.md

Updated blog post for the week of 24th of Oct

---

content/weekly-agenda/22-10-31/index.md

Publishing the  Weekly summary for 31st of Oct

---

content/weekly-agenda/22-10-24/index.md
content/weekly-agenda/22-10-31/index.md

removing the promoted status from old post

Removing old post as promoted

---

content/weekly-agenda/22-10-31/index.md

Updated demo for 3rd of Nov call

---

content/weekly-agenda/22-11-07/index.md

weekly summary for 7th of Nov

---

content/microsoft-365-pnp-weekly/episode-185/index.md

2022-11-04-added-podcast-to-pnpweekly-ep185

---

content/microsoft-365-platform-community-call/2022-11-01/index.md

adds reference

---

content/post/dynamic-use-of-adaptive-cards/index.md

There were no images included, I just added them to the index
- fixes #692 
Fixes images from my blogpost

Adding images to the index

---

content/post/dynamic-use-of-adaptive-cards/index.md

adds tn image

---

content/post/dynamic-use-of-adaptive-cards/index.md

Fixing formatting errors and broken image
- [x ] Content fix
- fixes #694 
Fixing formatting issues and removing broken image

Minor fixes

---

content/weekly-agenda/22-11-07/index.md
content/weekly-agenda/22-11-14/index.md

Weekly agenda for 14th of Nov week

---

content/microsoft-365-pnp-weekly/episode-187/index.md

added-activities-to-pnp-weekly-ep-187

---

content/post/microsoft-365-app-scenarios/index.md

Simple fix to also make title image visible: Fixing title image ref (jpg-->png)

Fixing title image ref (jpg-->png)

---

content/weekly-agenda/22-11-28/index.md

Weekly agenda for 28th of Nov week

---

content/weekly-agenda/22-11-21/index.md

adjusting blog posts which are promoted

---

content/microsoft-identity-platform-community-call/microsoft-identity-platform-community-call-november-2022/index.md

2022-12-03-remove-unused-attachment-tag-identity-platform-post

---

content/weekly-agenda/22-11-28/index.md
content/weekly-agenda/22-12-05/index.md
content/weekly-agenda/22-12-12/index.md

Weekly summary 12th of Dec

---

content/weekly-agenda/22-12-12/index.md

Including identity call topic to the weekly agenda.

Updating weekly summary with identity call agenda

---

content/weekly-agenda/22-12-12/index.md
content/weekly-agenda/22-12-19/index.md

weekly summary for 19th of Dec week

---

content/microsoft-365-platform-community-call/2022-12-20/index.md
content/power-platform-community-call/power-apps-community-call-december-2022/index.md

updated commits for blog posts

---

content/weekly-agenda/22-12-19/index.md
content/weekly-agenda/22-12-26/index.md

Weekly summary for the 26th of Dec week

---

content/weekly-agenda/23-01-02/index.md

Updating weekly agenda for the first week of 2023

---

content/microsoft-viva-and-spfx-community-call/2022-12-29/index.md

Fixing date for the 29th of Dec call post

---

content/weekly-agenda/22-12-26/index.md
content/weekly-agenda/23-01-02/index.md

Updating the trending post to blog

---

content/post/spfx-04-using-microsoft-graph-in-spfx-solutions/index.md

Fixing typo

---

content/weekly-agenda/23-01-09/index.md

Visibility of weekly summary 9th of Jan

---

content/microsoft-365-platform-community-call/2023-01-10/index,md

upsdate-front-matter-date-format-2023-01-10-platform-call-post

---

content/microsoft-365-platform-community-call/2023-01-03/index.md
content/microsoft-365-platform-community-call/2023-01-10/index,md

Fixing date formatting for 10th of Jan call recording post

---

content/microsoft-365-platform-community-call/2023-01-10/index.md

Investigating 10th of Jan publishing issue

---

content/post/spfx-06-spfx-for-teams/index.md
content/post/spfx-07-automatic-hosting-spfx-solutions/index.md

Fixing typos

---

content/microsoft-viva-and-spfx-community-call/2023-01-12/index.md

2023-01-12-spfx-post-reduce-words-in-description

---

content/microsoft-viva-and-spfx-community-call/2023-01-12/index.md

updated description again

---

content/weekly-agenda/23-01-09/index.md
content/weekly-agenda/23-01-16/index.md

Publishing weekly summary for 16th of Jan

---

content/weekly-agenda/23-01-16/index.md

Fixing title on weekly summary for 16th of Jan

---

content/post/spfx-10-single-part-app-pages/index.md

Release of SPFx part 10 article

---

content/post/spfx-10-single-part-app-pages/index.md

Fixing image for SPFx post part 10 article

---

content/post/How-to-create-a-button-in-a-Model-Driven-(Dataverse)-Power-App-that-launches-a-Power-Automate-Flow-in-a-Solution/index.md

Trying to fix the formatting issue on the blog

---

content/post/spfx-12-publishing-spfx-solutions-store/index.md

Fixing typo and copy-past issue

---

content/post/spfx-14-getting-started-with-pnpjs-spfx/index.md

Fixing random exception in publishing generated by GitHub

forcing new page generation

---

content/post/spfx-14-getting-started-with-pnpjs-spfx/index.md

GitHub issues - should be now finally going through.

Forcing new pages generation

---

content/post/spfx-14-getting-started-with-pnpjs-spfx/index.md

testing publishing

---

content/weekly-agenda/23-01-16/index.md
content/weekly-agenda/23-01-23/index.md

Weekly update for 23rd of Jan week

---

content/post/spfx-16-building-partner-offerings-for-viva-spfx/index.md

Fixing copy-paste issue

---

content/post/spfx-17-microsoft-graph-toolkit-spfx/index.md
content/post/spfx-18-reusable-open-source-controls-spfx/index.md

Publishing SPFx blog post 18

---

content/post/spfx-18-reusable-open-source-controls-spfx/index.md

Updating SPFx post 18 with links to video presenter profiles.

---

content/post/spfx-18-reusable-open-source-controls-spfx/index.md
content/post/spfx-19-professional-solutions-web-part-manifest/index.md

Getting Hugo's awesome article out

Publishing SPFx series part 19

---

content/post/spfx-19-professional-solutions-web-part-manifest/index.md

Publishing got paused last time - trying again.

restarting the publishing process

---

content/weekly-agenda/23-01-23/index.md
content/weekly-agenda/23-01-30/index.md

weekly update for 30th of Jan week

---

content/post/spfx-19-professional-solutions-web-part-manifest/index.md
content/post/spfx-20-professional-solutions-more-web-part-manifest-secrets/index.md

Publishing SPFx series part 20

---

content/post/spfx-21-professional-solutions-superb-solution-packages/index.md

Publishing SPFx series part 21

---

content/post/spfx-21-professional-solutions-superb-solution-packages/index.md

fixing top image for the SPFx part 21

---

content/microsoft-365-pnp-weekly/episode-195/index.md

correct-mispelling-pnp-weekly-ep195

---

content/post/spfx-22-do-more-with-less-microsoft365-spfx/index.md

Updating SPFx 22 article

---

content/weekly-agenda/23-01-30/index.md
content/weekly-agenda/23-02-06/index.md

Publishing weekly summary for the 6th of Feb week

---

config.toml

Updating naming conventions

---

content/post/microsoft-365-new-learn-ttk/index.md

Fixed broken links in the blog.
- [ x] Content fix

Fixed broken links to learn path

---

content/weekly-agenda/23-02-13/index.md
content/weekly-agenda/23-02-20/index.md

Weekly summary for the Feb 20th week

---

content/microsoft-365-pnp-weekly/episode-198/index.md

Publish PnP Weekly 198

---

content/microsoft-365-pnp-weekly/episode-199/index.md

add-podcast-to-pnp-weekly-ep-199

---

content/weekly-agenda/23-03-06/index.md

removing draft status

---

content/weekly-agenda/23-03-06/index.md

Fixing broken image

---

content/microsoft-365-platform-community-update/23-03-06/index.md

Publishing feb 23 monthly summary

---

content/microsoft-365-platform-community-call/2023-03-07/index.md

republish 7th of March call

---

content/weekly-agenda/23-03-06/index.md
content/weekly-agenda/23-03-13/index.md

Daylight saving note

---

content/cli-for-microsoft-365/cli-for-microsoft-365-v6-3/index.md
content/post/new-community-team-members-march-2023/index.md

Fixing Daniel's last name

---

content/post/ci-cd-spfx-deployment-azure-devops-m365-cli/index.md

Fixing image paths and markup for #1132 
Fixing blog post, images and code highlight war working incorectly

Typos and image paths of recent pull request

---

content/weekly-agenda/23-03-13/index.md
content/weekly-agenda/23-03-20/index.md

Weekly update for 20th of March week

---

content/microsoft-365-platform-community-call/2023-02-14/index.md
content/microsoft-365-platform-community-call/2023-02-21/index.md
content/microsoft-365-platform-community-call/2023-02-28/index.md
content/microsoft-365-platform-community-call/2023-03-07/index.md
content/microsoft-365-platform-community-call/2023-03-14/index.md
content/microsoft-365-platform-community-call/2023-03-21/index.md
content/weekly-agenda/23-03-20/index.md
content/weekly-agenda/23-03-27/index.md

Weekly agenda for 27th of March week

---

content/microsoft-365-pnp-weekly/episode-203/index.md

add-podcast-to-pnp-weekly-ep-203

---

content/microsoft-365-platform-community-call/2023-03-28/index.md

Fixing comma and date for call info

---

content/cli-for-microsoft-365/cli-for-microsoft-365-v6-4/index.md
content/post/new-community-team-members-march-2023/index.md

Replaces existing popular post
Fixes typos

CLI for Microsoft 365 v6.4 Fixes

---

content/microsoft-365-pnp-weekly/episode-204/index.md

Fixing few thing and adding context for the blog post

Update for the PnP Weekly episode 204 blog post

---

content/weekly-agenda/23-04-03/index.md
content/weekly-agenda/23-04-10/index.md

Weekly update for 10th of April

---

content/post/deploy-spfx-in-hub-site-and-associated-sites/index.md

Correct typo for category to community post

Update categories for blog post

---

content/weekly-agenda/23-04-17/index.md

weekly update for 17th

---

content/cli-for-microsoft-365/cli-for-microsoft-365-spring-cleaning-23/index.md

Fixed date and typo in 'CLI for Microsoft 365 spring cleaning'

Fixed date and typo in 'CLI for Microsoft 365 spring cleaning'

---

content/microsoft-viva-and-spfx-community-call/2023-04-20/index.md

add-key-links-to-2023-04-20-spfx-call-post

---

content/weekly-agenda/23-04-17/index.md
content/weekly-agenda/23-04-24/index.md

Publishing weekly summary for next week

---

content/weekly-agenda/23-04-17/index.md
content/weekly-agenda/23-04-24/index.md

Fixing publishing date

---

content/microsoft-365-pnp-weekly/episode-207/index.md

Updated food name with link

---

content/weekly-agenda/23-04-24/index.md
content/weekly-agenda/23-05-01/index.md
content/weekly-agenda/23-05-08/index.md

Weekly summary for 8th of May week

---

content/weekly-agenda/23-05-08/index.md
content/weekly-agenda/23-05-15/index.md

weekly summary update and publish

---

content/weekly-agenda/23-05-15/index.md
content/weekly-agenda/23-05-22/index.md

Weekly summary for community topics

---

content/microsoft-365-pnp-weekly/episode-211/index.md

edit-2023-05-22-front-matter-pnp-weekly-ep-211

---

content/weekly-agenda/23-05-21/index.md
content/weekly-agenda/23-05-22/index.md
content/weekly-agenda/23-05-29/index.md

Weekly summary for 29th of May week

---

content/weekly-agenda/23-05-29/index.md
content/weekly-agenda/23-06-05/index.md

weekly summery for first week of June

---

content/weekly-agenda/23-06-05/index.md
content/weekly-agenda/23-06-12/index.md

Weekly summary for 12th of June week

---

content/weekly-agenda/23-06-12/index.md
content/weekly-agenda/23-06-19/index.md

Weekly summary for 19th of June week

---

content/weekly-agenda/23-06-19/index.md
content/weekly-agenda/23-06-26/index.md

weekly update for 26th of June week

---

content/microsoft-viva-and-spfx-community-call/2023-06-29/index.md

draft-2023-06-29-spfx-call-post

---

content/post/2022-07-m365call-summer-schedule/index.md

post date fixes

---

content/cli-for-microsoft-365/cli-for-microsoft-365-v6-10/index.md
content/cli-for-microsoft-365/cli-for-microsoft-365-v6-9/index.md

Fixes typo

---

content/weekly-agenda/23-08-21/index.md

Updating 21st of August week

---

content/microsoft-365-pnp-weekly/episode-216/index.md

Updating date and agenda items for PnP Weekly episode 216

---

content/weekly-agenda/23-09-04/index.md

Weekly summary for 4th of Sep week

---

content/weekly-agenda/23-09-11/index.md

weekly agenda for 11th of Sep week

---

content/weekly-agenda/23-09-04/index.md
content/weekly-agenda/23-09-11/index.md
content/weekly-agenda/23-09-18/index.md

weekly agenda for 18th of Sep week

---

content/weekly-agenda/23-09-18/index.md

Initiating build

---

content/weekly-agenda/23-09-18/index.md

Adding Power Platform demo details

---

content/weekly-agenda/23-09-18/index.md
content/weekly-agenda/23-09-25/index.md

weekly summary for 25th of Sep

---

content/microsoft-365-pnp-weekly/episode-219/index.md

Publishing PnP Weekly episode 219

Finalizing episode 219

---

content/microsoft-365-pnp-weekly/episode-219/index.md
content/post/send-approval-in-teams-using-power-automate/index.md

Fixing publishing

---

content/weekly-agenda/23-10-02/index.md

Weekly plan for 2nd of October week

---

content/microsoft-365-pnp-weekly/episode-220/index.md

Fixing YouTube video embed

---

content/microsoft-365-pnp-weekly/episode-221/index.md

Initiate episode 221 publishing

---

content/weekly-agenda/23-10-09/index.md
content/weekly-agenda/23-10-16/index.md

Weekly community calls - details

---

content/weekly-agenda/23-10-16/index.md
content/weekly-agenda/23-10-23/index.md

weekly update

---

content/weekly-agenda/23-10-23/index.md

fixing date format

---

content/microsoft-365-pnp-weekly/episode-223/index.md

fixing article

---

content/microsoft-365-pnp-weekly/episode-223/index.md

Fixing 223 episode

---

content/weekly-agenda/23-11-06/index.md

Weekly agenda publishing

---

content/weekly-agenda/23-10-23/index.md
content/weekly-agenda/23-10-30/index.md
content/weekly-agenda/23-11-06/index.md
content/weekly-agenda/23-11-13/index.md

Weekly summary - 13th of Nov

---

content/microsoft-365-pnp-weekly/episode-229/index.md

fixing Agnes's twitter account

---

content/weekly-agenda/23-12-04/index.md
content/weekly-agenda/23-12-11/index.md

Weekly blog post for 11th of Dec

---

content/office-add-ins-community-call/2023-11-08/index.md

None.
Publishes the new blog post in https://github.com/pnp/blog/pull/1659.
None.

[Office Add-ins] Publish November community call blog post

---

content/weekly-agenda/23-12-11/index.md
content/weekly-agenda/23-12-18/index.md

Weekly blog post article

---

content/office-add-ins-community-call/2023-02-08/index.md
content/office-add-ins-community-call/2023-03-08/index.md

None.
Updates the categories to align with existing blog posts.
None.

[Office Add-ins] Update categories

---

content/weekly-agenda/23-12-25/index.md

weekly summary

---

content/microsoft-365-platform-community-update/23-06-06/index.md
content/post/Guide-to-demo-in-a-community-call/index.md
content/weekly-agenda/23-12-18/index.md
content/weekly-agenda/23-12-25/index.md

Updated promoted posts

---

content/post/how-to-use-react-hooks-with-sharepoint-framework-spfx-projects/index.md
content/post/sharepoint-framework-register-field-customizers-rest-api/index.md
content/post/sharepoint-framework-updated-in-sharepoint-server-subscription-edition/index.md
content/post/sharepoint-framework-v1-15-2-whats-in-latest-update-of-spfx/index.md

- n/a
Updates select canonical links to include trailing slash

🐞 fix canonical URLs

---

content/weekly-agenda/24-01-01/index.md
content/weekly-agenda/24-01-08/index.md

Wweekly update for 8th of Jan

---

content/microsoft-365-pnp-weekly/microsoft-365-pnp-weekly-episode-133-gautam-sheth-valo/index.md

♻️🔗 correct link references

---

content/weekly-agenda/24-01-08/index.md
content/weekly-agenda/24-01-15/index.md

Weekly summary 15th of Jan

---

content/weekly-agenda/24-01-15/index.md
content/weekly-agenda/24-01-22/index.md

Fixed 22nd of January week summary

---

content/microsoft-365-pnp-weekly/episode-233/index.md

Edit YouTube video link to match the correct episode.

PnP Weekly 233 - Edit YouTube video link

---

content/weekly-agenda/24-01-22/index.md
content/weekly-agenda/24-01-29/index.md

Weekly update for 29th of Jan

---

content/weekly-agenda/24-02-05/index.md

Latest weekly summary

---

content/weekly-agenda/24-01-29/index.md
content/weekly-agenda/24-02-05/index.md

call name typo for 8th of Feb

---

content/weekly-agenda/24-02-12/index.md

weekly summary for 12th of Feb week

---

content/post/how-to-generate-request-files-link-in-sharepoint-with-power-automate-for-anonymous-users-to-upload-files-in-specified-folders/index.md

The date of the post was incorrect and I just corrected it.

Updated post date

---

content/weekly-agenda/24-02-05/index.md
content/weekly-agenda/24-02-12/index.md
content/weekly-agenda/24-02-19/index.md

Weekly summary for 19th of Feb

---

content/microsoft-365-pnp-weekly/episode-237/index.md

Fixing video reference

---

content/weekly-agenda/24-02-19/index.md
content/weekly-agenda/24-02-26/index.md

26th of Feb week

---

content/weekly-agenda/24-03-04/index.md

fixing date

---

content/weekly-agenda/24-03-11/index.md

removing old article from trending

---

content/weekly-agenda/24-03-25/index.md

Weekly summary for 25th of March

---

content/microsoft-365-pnp-weekly/episode-243/index.md

Fixing issue on conflict resolution

---

content/weekly-agenda/24-04-01/index.md
content/weekly-agenda/24-04-08/index.md

pnp weekly 8th of week

---

content/post/new-community-team-members-april-2024/index.md

updating publishing time

---

content/post/new-community-team-members-april-2024/index.md

fixing wrong link for Reshmee

---

content/weekly-agenda/24-04-15/index.md

formatting fix

---

content/weekly-agenda/24-04-22/index.md

weekly update for 22nd of April week

---

content/weekly-agenda/24-04-15/index.md
content/weekly-agenda/24-04-22/index.md
content/weekly-agenda/24-04-29/index.md

Weekly agenda 29th of April

---

content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md

Updates CLI release blog post publish date

---

content/microsoft-365-pnp-weekly/episode-247/index.md

pnp weekly 247

---

content/weekly-agenda/24-05-06/index.md

Weekly summary for 6th of May week

---

content/microsoft-365-pnp-weekly/episode-248/index.md

Fixing missing twitter account for Ami

---

content/weekly-agenda/24-05-13/index.md

next week summary

---

content/weekly-agenda/24-05-13/index.md

fixing call time

---

content/microsoft-365-pnp-weekly/episode-249/index.md
content/weekly-agenda/24-05-13/index.md

Initiate publishing for the PnP Weekly blog post

---

content/microsoft-365-pnp-weekly/episode-249/index.md
content/weekly-agenda/24-04-29/index.md
content/weekly-agenda/24-05-06/index.md
content/weekly-agenda/24-05-13/index.md

Publishing of PnP Weekly 249

---

content/weekly-agenda/24-05-27/index.md
content/weekly-agenda/24-06-03/index.md
content/weekly-agenda/24-06-10/index.md

Weekly update for 10th of June week

---

.frontmatter/templates/microsoft-365-platform-call.md
content/cli-for-microsoft-365/cli-for-microsoft-365-v7-1/index.md
content/cli-for-microsoft-365/cli-for-microsoft-365-v7-2/index.md
content/cli-for-microsoft-365/cli-for-microsoft-365-v7-6/index.md
content/cli-for-microsoft-365/cli-for-microsoft-365-v7-7/index.md
content/cli-for-microsoft-365/cli-for-microsoft-365-v7-9/index.md
content/post/how-to-add-or-remove-owners-from-a-Power-Automate-flow-with-CLI-Microsoft365/index.md
content/post/multiple-node-installs-nvm-global-packages/index.md
content/post/spfx-21-professional-solutions-superb-solution-packages/index.md

- partially #1866
- cleanup SEO tags (consolidate to single standard
- missed a few in my last PR #1866

🧼 additional cleanup of tags

---

content/weekly-agenda/24-07-08/index.md
content/weekly-agenda/24-07-15/index.md
content/weekly-agenda/24-07-22/index.md
content/weekly-agenda/24-07-29/index.md
content/weekly-agenda/24-08-05/index.md

Updating post publishing date

---

content/office-add-ins-community-call/2024-04-10/index.md
content/office-add-ins-community-call/2024-05-08/index.md
content/office-add-ins-community-call/2024-06-12/index.md
content/office-add-ins-community-call/2024-07-10/index.md

Update the draft status. Change from true to false

Update blog draft status

---

content/weekly-agenda/24-08-26/index.md

Weekly summary for 26th of August

---

content/weekly-agenda/24-08-26/index.md

Adding Smita to agenda

---

content/post/changes-pnp-management-shell-registration/index.md

updated video link to the PnP Management shell

---

content/weekly-agenda/24-08-26/index.md
content/weekly-agenda/24-09-02/index.md

Weekly summary for September 2

---

content/cli-for-microsoft-365/cli-for-microsoft-365-v9-0/index.md
content/post/changes-pnp-management-shell-registration/index.md

Updates on the PnP management shell guidance

---

content/post/changes-pnp-management-shell-registration/index.md

post polishing

---

content/weekly-agenda/24-09-09/index.md
content/weekly-agenda/24-09-16/index.md

Publishing latest weekly summary

---

content/weekly-agenda/24-09-16/index.md

Polishing weekly post

---

content/weekly-agenda/24-09-23/index.md

Weekly agenda

---

content/weekly-agenda/24-09-16/index.md
content/weekly-agenda/24-09-23/index.md

Updating latest blog post draft false

---

content/weekly-agenda/24-09-23/index.md
content/weekly-agenda/24-09-30/index.md

Updating LinkedIn links

---

content/weekly-agenda/24-10-14/index.md
content/weekly-agenda/24-10-21/index.md

Weekly summary for 21st of Oct week

---

content/weekly-agenda/24-10-21/index.md
content/weekly-agenda/24-10-28/index.md

Weekly update for 28th of October

---

content/weekly-agenda/24-11-04/index.md
content/weekly-agenda/24-11-11/index.md

Publishing 11th of Nov weekly plan

---

content/weekly-agenda/24-11-11/index.md

Fixing date for the Thursday call

---

content/weekly-agenda/24-11-11/index.md
content/weekly-agenda/24-11-18/index.md

18th of Nov week update

---

content/weekly-agenda/24-11-18/index.md
content/weekly-agenda/24-11-25/index.md

25th of Nov week

---

content/weekly-agenda/24-11-25/index.md

updating date

---

content/post/spfx-solutions-as-spyware-part2/index.md

Adjusting post date to get article out

---

content/weekly-agenda/24-12-02/index.md
content/weekly-agenda/24-12-09/index.md

Weekly summary for 9th of Dec week

---

content/weekly-agenda/24-12-09/index.md
content/weekly-agenda/24-12-16/index.md

Weekly summary for 16th of Dec week

---

content/weekly-agenda/24-12-16/index.md
content/weekly-agenda/24-12-23/index.md

Weekly summary update

---

content/weekly-agenda/24-12-16/index.md
content/weekly-agenda/24-12-23/index.md

Fixing broken image link

---

content/weekly-agenda/24-12-23/index.md
content/weekly-agenda/24-12-30/index.md

weekly summary for week 53

---

content/weekly-agenda/24-12-30/index.md
content/weekly-agenda/25-01-06/index.md

Weekly update for 6th of Jan

---

content/weekly-agenda/25-01-06/index.md
content/weekly-agenda/25-01-13/index.md

Weekly update publishing

---

content/weekly-agenda/25-01-13/index.md

Fixing date typo

---

content/weekly-agenda/25-01-13/index.md
content/weekly-agenda/25-01-20/index.md

Weekly update for 20th of Jan

---

content/post/how-to-use-the-usereducer-hook-for-managing-complex-state-in-spfx-projects-step-by-step-guide/index.md

Fixing broken image reference

---

.github/workflows/site-production-build-deploy.yml

Updates action versions to latest

Fixes build a deploy workflow

---

content/cli-for-microsoft-365/cli-for-microsoft-365-v10-3/index.md

Fixes some CLI for Microsoft 365 v10.3.0 typos

---

content/post/azuredevops-powerplatform-workloadidentityfederation/images/index.md

Updates azuredevops-powerplatform-workloadidentityfederation blog post release date to make it visible on blog post like now 😉

Update azuredevops-powerplatform-workloadidentityfederation release date

---

content/weekly-agenda/25-02-03/index.md

Updating Nish's demo title for 6th of Feb

---

content/weekly-agenda/25-02-10/index.md
content/weekly-agenda/25-02-17/index.md

Weekly update for 17th of Feb week

---

content/weekly-agenda/25-02-17/index.md

Name update

---

content/post/spfx-setup-part2-wsl/index.md

Fixes wrongly set release date for the SPFx setup part 2 blog post

---

content/weekly-agenda/25-02-10/index.md
content/weekly-agenda/25-02-17/index.md
content/weekly-agenda/25-02-24/index.md

Week on 24th of Feb

---

content/weekly-agenda/25-03-10/index.md

March 10 publish

---

content/weekly-agenda/25-03-03/index.md
content/weekly-agenda/25-03-10/index.md
content/weekly-agenda/25-03-17/index.md

Updated 17th  of March summary

---

content/post/spfx-setup-part2-wsl/index.md

Added info how to setup for dev cert for `gulp serve` on WSL

Updates WSL SPFx setup blog post

---

content/post/create-report-of-assigned-licenses-to-users-from-microsoft-365/index.md

blog post - Create Report Of Assigned Licenses To Users From Microsoft 365
the majority of image links were broken
- fixes #1989 
fixed images links desribed in the issue #1989. verified and fixed all links and not just the one mentioned in the issue description

fixed broken image ref links in the blog post

---

content/weekly-agenda/25-03-31/index.md
content/weekly-agenda/25-04-07/index.md

Weekly update - getting public

---

content/weekly-agenda/25-03-03/index.md

Adjusting old post type

---

content/weekly-agenda/25-04-07/index.md
content/weekly-agenda/25-04-14/index.md

Weekly summary for 14th of April

---

content/pnp-powershell/pnp-powershell-v3-0-0/index.md

Fixed title

---

content/weekly-agenda/25-05-05/index.md

Weekly summary plan

---

content/weekly-agenda/25-05-12/index.md
content/weekly-agenda/25-05-19/index.md

Including latest community call

---

content/weekly-agenda/25-05-19/index.md
content/weekly-agenda/25-05-26/index.md

Update on the weekly summary

---

content/weekly-agenda/25-07-14/index.md

Added Golnoosh to Agenda with Franck

Added Golnoosh to Agenda with Franck

---

content/post/credly-names-our-recognition-program-best-in-class/index.md

Updated the category to be dedicated for the Recognition Program

Best in class blog updates

---

content/weekly-agenda/25-09-01/index.md

Weekly summary for 1st of Sep week

---

content/weekly-agenda/25-09-01/index.md

Updating latest weekly as trending

---

content/weekly-agenda/25-09-29/index.md
content/weekly-agenda/25-10-06/index.md

Weekly summary update for 6th of Oct week
